#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Manuel Morejón

# Short bio or description (displayed in the header)
description: Gestor de Configuración de Software

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/5578317?v=3&s=460

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:  manuel.morejon.85@gmail.com
  facebook: manuel.m.espinosa.3
  flickr:
  github: mmorejon
  instagram:
  linkedin: manuelmorejon
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter:  morejon85
  stackoverflow:  # users/4142357/manuel-morejón # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: mmorejon

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-54661232-3

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

defaults:
  # Default language
  -
    scope:
      path: ""
    values:
      lang: "es"
  # Language for everything inside `/en`
  -
    scope:
      path: "en"
    values:
      lang: "en"
  # Language for English posts
  -
    scope:
      path: "en/_posts"
      type: "posts" # As of version 2.3.0, Jekyll uses plural keywords for type
    values:
      lang: "en"
#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:categories/:year/:month/:title

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed or the value by default :expanded

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jemoji # Transform text in images

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
